# Generated by Django 5.1.5 on 2025-01-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='baner',
            field=models.ImageField(blank=True, default='fall.png', upload_to=''),
        ),
    ]
